/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.jsx",
    "./src/**/*.js",
    "./src/**/*.tsx",
    "./src/**/*.ts",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed":          "#291800",
        "primary-fixed":             "#ffddb4",
        "inverse-surface":           "#e5e2e1",
        "on-primary-fixed-variant":  "#633f00",
        "surface-container-lowest":  "#0e0e0e",
        "surface-bright":            "#3a3939",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant":"#474746",
        "on-secondary-container":    "#b7b4b4",
        "outline-variant":           "#524534",
        "tertiary-fixed":            "#e4e2e1",
        "background":                "#0D0D0D",
        "tertiary-fixed-dim":        "#c8c6c5",
        "on-tertiary-fixed-variant": "#474746",
        "error":                     "#ffb4ab",
        "tertiary":                  "#d4d1d1",
        "surface-variant":           "#353534",
        "on-error-container":        "#ffdad6",
        "surface":                   "#0D0D0D",
        "tertiary-container":        "#b8b6b6",
        "on-tertiary":               "#303030",
        "secondary":                 "#c8c6c5",
        "on-primary":                "#452b00",
        "surface-container":         "#201f1f",
        "on-surface-variant":        "#d7c3ae",
        "on-secondary-fixed":        "#1c1b1b",
        "inverse-primary":           "#835500",
        "on-primary-container":      "#644000",
        "primary":                   "#ffc880",
        "secondary-fixed":           "#e5e2e1",
        "on-background":             "#e5e2e1",
        "primary-fixed-dim":         "#ffb955",
        "secondary-container":       "#474746",
        "on-secondary":              "#313030",
        "surface-dim":               "#131313",
        "on-error":                  "#690005",
        "on-tertiary-fixed":         "#1b1c1c",
        "on-tertiary-container":     "#484747",
        "surface-container-low":     "#1c1b1b",
        "surface-tint":              "#ffb955",
        "surface-container-high":    "#2a2a2a",
        "on-surface":                "#e5e2e1",
        "outline":                   "#9f8e7a",
        "error-container":           "#93000a",
        "secondary-fixed-dim":       "#c8c6c5",
        "inverse-on-surface":        "#313030",
        "primary-container":         "#f5a623",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        gutter:            "24px",
        stack_md:          "16px",
        sidebar_width:     "240px",
        right_panel_width: "300px",
        stack_lg:          "32px",
        container_padding: "40px",
        stack_sm:          "8px",
      },
      fontFamily: {
        "display-lg":   ["Playfair Display", "serif"],
        "label-sm-caps":["Inter", "sans-serif"],
        "headline-lg":  ["Playfair Display", "serif"],
        "title-md":     ["Inter", "sans-serif"],
        "body-md":      ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg":    ["48px", { lineHeight:"1.2", letterSpacing:"-0.02em", fontWeight:"700" }],
        "label-sm-caps": ["12px", { lineHeight:"1",   letterSpacing:"0.1em",  fontWeight:"700" }],
        "headline-lg":   ["32px", { lineHeight:"1.3", fontWeight:"600" }],
        "title-md":      ["18px", { lineHeight:"1.5", fontWeight:"600" }],
        "body-md":       ["16px", { lineHeight:"1.6", fontWeight:"400" }],
      },
      animation: {
        "breath":      "breath 3s ease-in-out infinite",
        "pulse-amber": "pulseAmber 4s cubic-bezier(0.4,0,0.6,1) infinite",
        "ai-breath":   "breath 3s ease-in-out infinite",
      },
      keyframes: {
        breath: {
          "0%, 100%": { opacity:"0.6", transform:"scale(1)" },
          "50%":      { opacity:"1",   transform:"scale(1.02)" },
        },
        pulseAmber: {
          "0%, 100%": { boxShadow:"0 0 0 0 rgba(245,166,35,0)" },
          "50%":      { boxShadow:"0 0 15px 2px rgba(245,166,35,0.2)" },
        },
      },
    },
  },
  plugins: [],
}